# Problem Set 03 (Total 40 pts)

---

## Problem 01 (5 pts)

Create the following 2D numpy array (named X) without typing it explicitly

```
array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])
```

In [ ]:
# Write your code here to answer the question

#

## Problem 02 (5 pts)

Build a 5 x 5 array of ones (named `Y`). Divide each element in the array by the sum of indicies (row and column) plus 1 and reassign the element in the array Y.

Hint: row 2 (`Y[2]`) should equal 
```
array([0.33333333, 0.25, 0.2, 0.16666667, 0.14285714])
```

In [ ]:
# Write your code here to answer the question

#

##  Problem 03 (10 pts)

Create a function, `sort_2d_arrays()`, that takes in a numpy array as an argument. This funtion will do the following: 
- checks if the array is 2D
- If the check fails it will print `The array in not 2D` and returns nothing
- If the check passes then the function prints 
    - the original array
    - the array sorted by columns
    - the array sorted by rows
    - flattened and sorted 1D array.
- The output should look like this:
```
Original array:
 [[1 5 3 7]
 [7 2 2 9]]
Array sorted by column:
 [[1 2 2 7]
 [7 5 3 9]]
Array sorted by row:
 [[1 3 5 7]
 [2 2 7 9]]
Flattened and sorted array:
 [1 2 2 3 5 7 7 9]
```

In [ ]:
# Write your code here to answer the question

#

## Problem 04 (20 pts)

Create a function, `find_mid()`, that takes in two arguments: number of rows (`i`) and number of columns (`j`). The function then builds a random matrix (values between 0 and 1), identifies the value in each row that is closest to 0.5, then prints the index and value of that item in each row.

For example, the function `find_mid(2,2)` will output:

```
Row 0: Item 0 (0.1254598811526375) is closest to 0.5
Row 1: Item 1 (0.0986584841970366) is closest to 0.5 
```

P.S. Don't forget to set the random seed so your function is deterministic.

In [ ]:
# Write your code here to answer the question

#